palette = "gruvbox_material"

add_newline = true

format = "$directory $git_branch $character"

[character]
success_symbol = "[➜](bold @gruvbox_material.green)"
error_symbol = "[➜](bold @gruvbox_material.red)"

[directory]
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
symbol = " "
style = "fg:@gruvbox_material.green"
format = "[$symbol$branch]($style)"

# >>> NOCTALIA STARSHIP PALETTE >>>
[palettes.gruvbox_material]
blue      = "#7daea3"
red       = "#e67e80"
green     = "#a9b665"
yellow    = "#d8a657"
cyan      = "#83a598"
magenta   = "#d3869b"
white     = "#ddc7a1"
black     = "#282828"
rosewater = "#d8a657"
flamingo  = "#e67e80"
pink      = "#d3869b"
mauve     = "#d3869b"
maroon    = "#e67e80"
peach     = "#d8a657"
teal      = "#a9b665"
sky       = "#7daea3"
sapphire  = "#7daea3"
lavender  = "#d3869b"
text      = "#ddc7a1"
subtext1  = "#bdae93"
subtext0  = "#a89984"
overlay2  = "#a89984"
overlay1  = "#bdae93"
overlay0  = "#504945"
surface2  = "#504945"
surface1  = "#3c3836"
surface0  = "#32302f"
base      = "#282828"
mantle    = "#282828"
crust     = "#1d2021"
# <<< NOCTALIA STARSHIP PALETTE <<<
