describe("blade snippets", function()
  it("should be able to require config.snippets.blade", function()
    local ok, blade = pcall(require, "config.snippets.blade")
    assert.is_true(ok, "config.snippets.blade module should be loadable")
    assert.is_table(blade, "config.snippets.blade should be a table")
  end)

  it("should return a table with snippets", function()
    local blade = require("config.snippets.blade")
    assert.is_table(blade, "module should return a table")
    assert.is_not_empty(blade, "module table should not be empty")
  end)
end)
