# Enable IPC so you can switch wallpapers on the fly
ipc = on
splash = false

# Wallpaper configuration
wallpaper {
    monitor = 
    path = /home/alejandrocabeza/.dotfiles/wallpapers/surreal-cherry-3840x2160-26233.jpg
    fit_mode = cover
}
