# ============================================
# hyprlauncher configuration
# Aspecto tipo Alfred (macOS)
# ============================================

# General
grab_focus = true

# Cache (frecuencia de uso)
cache {
    enabled = true
}

# Finders / Módulos
default_finder = desktop

desktop_prefix =           
unicode_prefix = .         
math_prefix    = =         
font_prefix    = '         

desktop_launch_prefix =    
desktop_icons = true       

# UI - Tamaño tipo Alfred (ancho, alto)
window_size = 800 480
