general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
}

# Screensaver tras 2.5 min
listener {
    timeout = 150
    on-timeout = hyprlock
}

# Bloqueo tras 5 min
listener {
    timeout = 300
    on-timeout = hyprlock
}
