color0 #16130e
color1 #ffb4ab
color2 #ffba4b
color3 #ddc2a1
color4 #b7cea2
color5 #ffba4b
color6 #ddc2a1
color7 #eae1d9
color8 #9b8f80
color9 #ffb4ab
color10 #ffba4b
color11 #ddc2a1
color12 #b7cea2
color13 #ffba4b
color14 #ddc2a1
color15 #eae1d9

cursor                #eae1d9
cursor_text_color     #16130e
background            #16130e
foreground            #eae1d9
selection_foreground  #d3c4b4
selection_background  #4f4539
active_border_color   #ffba4b
inactive_border_color #4f4539
url_color             #ffba4b

active_tab_foreground   #442b00
active_tab_background   #ffba4b
inactive_tab_foreground #d3c4b4
inactive_tab_background #4f4539
cursor_trail_color      #d3c4b4
