color0 #faf9fd
color1 #ba1a1a
color2 #315da8
color3 #575e71
color4 #715573
color5 #adc6ff
color6 #bfc6dc
color7 #1b1b1f
color8 #74777f
color9 #ba1a1a
color10 #315da8
color11 #575e71
color12 #715573
color13 #adc6ff
color14 #bfc6dc
color15 #1b1b1f

cursor                #1b1b1f
cursor_text_color     #faf9fd
background            #faf9fd
foreground            #1b1b1f
selection_foreground  #44474f
selection_background  #e1e2ec
active_border_color   #315da8
inactive_border_color #e1e2ec
url_color             #315da8

active_tab_foreground   #ffffff
active_tab_background   #315da8
inactive_tab_foreground #44474f
inactive_tab_background #e1e2ec
cursor_trail_color      #44474f
