color0 #161215
color1 #ffb4ab
color2 #fface8
color3 #dcbed0
color4 #f5b9a3
color5 #fface8
color6 #dcbed0
color7 #eae0e3
color8 #9b8d94
color9 #ffb4ab
color10 #fface8
color11 #dcbed0
color12 #f5b9a3
color13 #fface8
color14 #dcbed0
color15 #eae0e3

cursor                #eae0e3
cursor_text_color     #161215
background            #161215
foreground            #eae0e3
selection_foreground  #d2c2ca
selection_background  #4f444a
active_border_color   #fface8
inactive_border_color #4f444a
url_color             #fface8

active_tab_foreground   #57124d
active_tab_background   #fface8
inactive_tab_foreground #d2c2ca
inactive_tab_background #4f444a
cursor_trail_color      #d2c2ca
